//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CasePC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CasePC()
        {
            this.CauHinhPCs = new HashSet<CauHinhPC>();
        }
    
        public string MaCase { get; set; }
        public string Model { get; set; }
        public int ChieuDai { get; set; }
        public int ChieuRong { get; set; }
        public int ChieuCao { get; set; }
        public string HangSX { get; set; }
        public int Giaban { get; set; }
        public int Diem { get; set; }
        public double DanhGia { get; set; }
        public string URL { get; set; }
    
        public virtual HangSX HangSX1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHinhPC> CauHinhPCs { get; set; }
    }
}
