//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CPU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CPU()
        {
            this.CauHinhPCs = new HashSet<CauHinhPC>();
        }
    
        public string MaCPU { get; set; }
        public string HangSX { get; set; }
        public string Model { get; set; }
        public string Socket { get; set; }
        public Nullable<int> SoNhan { get; set; }
        public Nullable<int> SoLuong { get; set; }
        public double XungNhip { get; set; }
        public string Dohoa { get; set; }
        public string DongCPU { get; set; }
        public int Cache { get; set; }
        public int Giaban { get; set; }
        public int Diennang { get; set; }
        public int Diem { get; set; }
        public double DanhGia { get; set; }
        public string URL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHinhPC> CauHinhPCs { get; set; }
        public virtual DongCPU DongCPU1 { get; set; }
        public virtual HangSX HangSX1 { get; set; }
    }
}
