//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGia
    {
        public string MaDanhGia { get; set; }
        public string MaUser { get; set; }
        public byte[] TGDanhGia { get; set; }
        public double DiemTong { get; set; }
        public Nullable<double> DiemCPU { get; set; }
        public string MaCPU { get; set; }
        public Nullable<double> DiemGPU { get; set; }
        public string MaGPU { get; set; }
        public Nullable<double> DiemMain { get; set; }
        public string MaMain { get; set; }
        public Nullable<double> DiemHDD { get; set; }
        public string MaHDD { get; set; }
        public Nullable<double> DiemRam { get; set; }
        public string MaRam { get; set; }
        public string Binhluan { get; set; }
    
        public virtual GPU GPU { get; set; }
        public virtual HDD HDD { get; set; }
        public virtual Mainboard Mainboard { get; set; }
        public virtual RAM RAM { get; set; }
        public virtual User User { get; set; }
    }
}
