//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HDD
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public HDD()
        {
            this.CauHinhPCs = new HashSet<CauHinhPC>();
            this.CauHinhPCs1 = new HashSet<CauHinhPC>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public string MaHDD { get; set; }
        public string Model { get; set; }
        public string LoaiOCung { get; set; }
        public string HangSX { get; set; }
        public int DungLuong { get; set; }
        public string ChuanKetNoi { get; set; }
        public Nullable<int> TocDoDoc { get; set; }
        public Nullable<int> TocDoGhi { get; set; }
        public int Diem { get; set; }
        public double DanhGia { get; set; }
        public string URL { get; set; }
        public int Giaban { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHinhPC> CauHinhPCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHinhPC> CauHinhPCs1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual HangSX HangSX1 { get; set; }
    }
}
