//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Mainboard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Mainboard()
        {
            this.CauHinhPCs = new HashSet<CauHinhPC>();
            this.DanhGias = new HashSet<DanhGia>();
        }
    
        public string MaMain { get; set; }
        public string HangSX { get; set; }
        public string Model { get; set; }
        public string Socket { get; set; }
        public string Chipset { get; set; }
        public int RamToiDa { get; set; }
        public string PCI { get; set; }
        public int SoKheRam { get; set; }
        public int Giaban { get; set; }
        public string LoaiRamToiDa { get; set; }
        public double DanhGia { get; set; }
        public int Diem { get; set; }
        public string URL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHinhPC> CauHinhPCs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DanhGia> DanhGias { get; set; }
        public virtual HangSX HangSX1 { get; set; }
        public virtual LoaiRam LoaiRam { get; set; }
    }
}
