//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Nguon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Nguon()
        {
            this.CauHinhPCs = new HashSet<CauHinhPC>();
        }
    
        public string MaNguon { get; set; }
        public string Model { get; set; }
        public string HangSX { get; set; }
        public int CongSuat { get; set; }
        public Nullable<int> HieuSuat { get; set; }
        public int Giaban { get; set; }
        public int Diem { get; set; }
        public double Danhgia { get; set; }
        public string URL { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CauHinhPC> CauHinhPCs { get; set; }
        public virtual HangSX HangSX1 { get; set; }
    }
}
