//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuildPC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanMem
    {
        public string MaPM { get; set; }
        public string TenPM { get; set; }
        public string CHToiThieu { get; set; }
        public string CHKhuyenNghi { get; set; }
        public string LoaiPM { get; set; }
    
        public virtual CauHinhPC CauHinhPC { get; set; }
        public virtual CauHinhPC CauHinhPC1 { get; set; }
    }
}
